name: General bug report
description: Report a bug in the project when you're not sure about the exact and precise details of the problem.
title: "[Bug report]: "

projects: ["BugDotNet/3"]
type: "Bug report"

body:
  - type: checkboxes
    id: code-of-conduct
    attributes:
      label: Read and agreed to follow our Code of Conduct?
      description: |
        Have you read our [Code of Conduct](https://github.com/BugDotNet/.github/blob/main/.github/code_of_conduct.md) and do you agree to follow it?
        **Please make sure you actually read it, as it contains many helpful tips for effective communication.**
      options:
        - label: I have read the Code of Conduct and I agree to follow it.
          required: true

  - type: checkboxes
    id: existing-bug-reports
    attributes:
      label: Checked the existing bug reports?
      description: "Have you checked the existing bug reports to see if your issue has already been reported?"
      options:
        - label: I have checked the existing bug reports to see if my issue has already been reported.
          required: true



  - type: textarea
    id: description
    attributes:
      label: The problem
      description: "Please describe the issue that you have noticed and would like to report."
    validations:
      required: true



  - type: markdown
    attributes:
      value: "Thank you for taking the time to fill out a bug report."
